# pyproject.toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "TensorCollab"
version = "0.1.0"
description = "Package for the Tensor-Collab CAADi"
authors = [
  { name = "Raul Gomez", email = "rgomez@tec.mx" }
]
dependencies = [
  "numpy",
  "matplotlib",
  "scipy",
  "tensorflow",
  "pandas",
  "jupyter",
  "nbconvert",
  "pyyaml",
  "ipywidgets",
  "scikit-learn"
]

[project.scripts]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

